[GLOBAL]
pants_version = "2.13.0"

backend_packages.add = [
  "pants.backend.awslambda.python",
  "pants.backend.docker",
  "pants.backend.python",
]

use_deprecated_directory_cli_args_semantics = false

[source]
root_patterns = [
  '/project',
]

[anonymous-telemetry]
enabled = false